# Generated by Django 5.2.11 on 2026-02-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_tableqr_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableqr',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_map', to='menu.table'),
        ),
    ]
